name: py38
channels:
  - pytorch
  - acellera
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - _py-xgboost-mutex=2.0=cpu_0
  - bcftools=1.9=ha228f0b_4
  - binutils_impl_linux-64=2.33.1=he6710b0_7
  - binutils_linux-64=2.33.1=h9595d00_15
  - blas=1.0=mkl
  - bottleneck=1.3.4=py38hce1f21e_0
  - brotli=1.0.9=he6710b0_2
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2022.4.26=h06a4308_0
  - certifi=2022.5.18.1=py38h06a4308_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - curl=7.82.0=h7f8727e_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.4.4=h295c915_0
  - ffmpeg=4.2.2=h20bf706_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_15
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_15
  - h5py=3.6.0=py38ha0f2276_0
  - hdf5=1.10.6=hb1b8bf9_0
  - hdf5storage=0.1.16=pyh44b312d_0
  - icu=58.2=he6710b0_3
  - intel-openmp=2021.4.0=h06a4308_3561
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.3.2=py38h295c915_0
  - krb5=1.19.2=hac12032_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libcurl=7.82.0=h0b77cf5_0
  - libdeflate=1.0=h14c3975_1
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libgpuarray=0.7.6=h7f8727e_1
  - libidn2=2.3.2=h7f8727e_0
  - libllvm11=11.1.0=h3826bc1_1
  - libnghttp2=1.46.0=hce63b2e_0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.1.0=h2733197_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.40.0=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.2.0=h89dd481_0
  - libxcb=1.14=h7b6447c_0
  - libxgboost=1.5.0=h295c915_1
  - libxml2=2.9.12=h74e7548_1
  - llvmlite=0.38.0=py38h4ff587b_0
  - lz4-c=1.9.3=h295c915_1
  - mako=1.1.4=pyhd3eb1b0_0
  - markupsafe=2.0.1=py38h27cfd23_0
  - matplotlib=3.5.1=py38h06a4308_1
  - matplotlib-base=3.5.1=py38ha18d171_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - moleculekit=0.8.2=py38_0
  - munkres=1.1.4=py_0
  - ncurses=6.3=h7f8727e_2
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - numba=0.55.1=py38h51133e4_0
  - numexpr=2.8.1=py38h6abb31d_0
  - numpy=1.21.5=py38he7a7128_2
  - numpy-base=1.21.5=py38hf524024_2
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1o=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.2=py38h295c915_0
  - pcre=8.45=h295c915_0
  - perl=5.26.2=h14c3975_0
  - perl-vcftools-vcf=0.1.16=pl526_2
  - pip=21.2.4=py38h06a4308_0
  - py-xgboost=1.5.0=py38h06a4308_1
  - pygpu=0.7.6=py38hce1f21e_1
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h05f1152_4
  - python=3.8.13=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytorch=1.10.1=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pytz=2021.3=pyhd3eb1b0_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.1.2=h7f8727e_1
  - scikit-learn=1.0.2=py38h51133e4_1
  - scipy=1.7.3=py38hc147768_0
  - setuptools=61.2.0=py38h06a4308_0
  - sip=4.19.13=py38h295c915_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.3=hc218d9a_0
  - tbb=2021.5.0=hd09550d_0
  - theano=1.0.4=py38hfd86e86_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.11=h1ccaba5_1
  - torchaudio=0.10.1=py38_cu113
  - torchvision=0.11.2=py38_cu113
  - tornado=6.1=py38h27cfd23_0
  - tqdm=4.64.0=py38h06a4308_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - x264=1!157.20191217=h7b6447c_0
  - xgboost=1.5.0=py38h06a4308_1
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.4.9=haebb681_0
  - pip:
    - flatbuffers==2.0
    - imageio==2.13.1
    - keras==2.7.0
    - libauc==1.1.6
    - libclang==12.0.0
    - networkx==2.6.3
    - opencv-python==4.5.4.60
    - pillow==8.4.0
    - pywavelets==1.2.0
    - scikit-image==0.19.0
    - tensorflow==2.7.0
    - tensorflow-estimator==2.7.0
    - tensorflow-io-gcs-filesystem==0.22.0
    - tifffile==2021.11.2
    - wget==3.2
prefix: /scratch/user/wuwei_tan/.conda/envs/py38
